# РАСПРЕДКОРОБКА СПАЛЬНИ
bedroom_box: Распредкоробка Спальня {
  shape: rectangle
  width: 120
  height: 200
  style: {
    stroke: "#666666"
    fill: "#F5F5F5"
    stroke-width: 2
  }

  # Входные линии
  power: Питание


  switch1: Выключатель проходной люстра
  switch2: Выключатель проходной споты



}

  bedroom_box.power -> bedroom.socket_tv
  bedroom_box.power -> bedroom.socket_1
  bedroom_box.power -> bedroom.socket_2
  bedroom_box.power -> bedroom.ac
  bedroom_box.power -> bedroom.socket_tv


  bedroom_box.switch1 -> bedroom.switch_entrance
  bedroom_box.switch1 -> bedroom.switch_bed
  bedroom_box.switch1 -> bedroom.chandelier

  bedroom_box.switch2 -> bedroom.switch_entrance
  bedroom_box.switch2 -> bedroom.switch_bed
  bedroom_box.switch2 -> bedroom.spots

bedroom: СПАЛЬНЯ {
  shape: rectangle
  style: {
    fill: "#E8F5E9"
  }
  chandelier: 💡 Люстра
  spots: 💡 Споты

  socket_tv: 🔌 Розетка TV
  socket_1: 🔌 Розетка 1
  socket_2: 🔌 Розетка 2
  ac: ❄️ Кондиционер
  switch_entrance: 🔘 Выключатель вход (2x кнопочный)
  switch_bed: 🔘 Выключатель кровать (2x кнопочный)
}