# СХЕМА РАСПРЕДЕЛЕНИЯ ЭЛЕКТРОПРОВОДКИ ПО КОМНАТАМ

layout: elk
direction: right

# Импорт всех модулей
import: "./modules/main_panel.d2"
import: "./modules/smart_hub.d2"
import: "./modules/bedroom.d2"
import: "./modules/kids_room.d2"
import: "./modules/hallway.d2"
import: "./modules/bathroom1.d2"
import: "./modules/bathroom2.d2"
import: "./modules/connections.d2"